using System;
using System.Collections.Generic;
using System.Linq;

namespace Backend.Helpers
{
    public sealed record CountryEntry(string Name, string IsoCode, string DialCode);

    public static class CountryCatalog
    {
        public static readonly IReadOnlyList<CountryEntry> Countries = new List<CountryEntry>
        {
            new("Afghanistan", "AF", "+93"),
            new("Albania", "AL", "+355"),
            new("Algeria", "DZ", "+213"),
            new("American Samoa", "AS", "+1"),
            new("Andorra", "AD", "+376"),
            new("Angola", "AO", "+244"),
            new("Anguilla", "AI", "+1"),
            new("Antarctica", "AQ", "+672"),
            new("Antigua and Barbuda", "AG", "+1"),
            new("Argentina", "AR", "+54"),
            new("Armenia", "AM", "+374"),
            new("Aruba", "AW", "+297"),
            new("Australia", "AU", "+61"),
            new("Austria", "AT", "+43"),
            new("Azerbaijan", "AZ", "+994"),
            new("Bahamas", "BS", "+1"),
            new("Bahrain", "BH", "+973"),
            new("Bangladesh", "BD", "+880"),
            new("Barbados", "BB", "+1"),
            new("Belarus", "BY", "+375"),
            new("Belgium", "BE", "+32"),
            new("Belize", "BZ", "+501"),
            new("Benin", "BJ", "+229"),
            new("Bermuda", "BM", "+1"),
            new("Bhutan", "BT", "+975"),
            new("Bolivia", "BO", "+591"),
            new("Bonaire, Sint Eustatius and Saba", "BQ", "+599"),
            new("Bosnia and Herzegovina", "BA", "+387"),
            new("Botswana", "BW", "+267"),
            new("Bouvet Island", "BV", "+47"),
            new("Brazil", "BR", "+55"),
            new("British Indian Ocean Territory", "IO", "+246"),
            new("Brunei", "BN", "+673"),
            new("Bulgaria", "BG", "+359"),
            new("Burkina Faso", "BF", "+226"),
            new("Burundi", "BI", "+257"),
            new("Cambodia", "KH", "+855"),
            new("Cameroon", "CM", "+237"),
            new("Canada", "CA", "+1"),
            new("Cape Verde", "CV", "+238"),
            new("Cayman Islands", "KY", "+1"),
            new("Central African Republic", "CF", "+236"),
            new("Chad", "TD", "+235"),
            new("Chile", "CL", "+56"),
            new("China", "CN", "+86"),
            new("Christmas Island", "CX", "+61"),
            new("Cocos (Keeling) Islands", "CC", "+61"),
            new("Colombia", "CO", "+57"),
            new("Comoros", "KM", "+269"),
            new("Congo (Democratic Republic of the)", "CD", "+243"),
            new("Congo (Republic of the)", "CG", "+242"),
            new("Cook Islands", "CK", "+682"),
            new("Costa Rica", "CR", "+506"),
            new("Cote d'Ivoire", "CI", "+225"),
            new("Croatia", "HR", "+385"),
            new("Cuba", "CU", "+53"),
            new("Curacao", "CW", "+599"),
            new("Cyprus", "CY", "+357"),
            new("Czechia", "CZ", "+420"),
            new("Denmark", "DK", "+45"),
            new("Djibouti", "DJ", "+253"),
            new("Dominica", "DM", "+1"),
            new("Dominican Republic", "DO", "+1"),
            new("Ecuador", "EC", "+593"),
            new("Egypt", "EG", "+20"),
            new("El Salvador", "SV", "+503"),
            new("Equatorial Guinea", "GQ", "+240"),
            new("Eritrea", "ER", "+291"),
            new("Estonia", "EE", "+372"),
            new("Eswatini", "SZ", "+268"),
            new("Ethiopia", "ET", "+251"),
            new("Falkland Islands", "FK", "+500"),
            new("Faroe Islands", "FO", "+298"),
            new("Fiji", "FJ", "+679"),
            new("Finland", "FI", "+358"),
            new("France", "FR", "+33"),
            new("French Guiana", "GF", "+594"),
            new("French Polynesia", "PF", "+689"),
            new("French Southern Territories", "TF", "+262"),
            new("Gabon", "GA", "+241"),
            new("Gambia", "GM", "+220"),
            new("Georgia", "GE", "+995"),
            new("Germany", "DE", "+49"),
            new("Ghana", "GH", "+233"),
            new("Gibraltar", "GI", "+350"),
            new("Greece", "GR", "+30"),
            new("Greenland", "GL", "+299"),
            new("Grenada", "GD", "+1"),
            new("Guadeloupe", "GP", "+590"),
            new("Guam", "GU", "+1"),
            new("Guatemala", "GT", "+502"),
            new("Guernsey", "GG", "+44"),
            new("Guinea", "GN", "+224"),
            new("Guinea-Bissau", "GW", "+245"),
            new("Guyana", "GY", "+592"),
            new("Haiti", "HT", "+509"),
            new("Heard Island and McDonald Islands", "HM", "+672"),
            new("Honduras", "HN", "+504"),
            new("Hong Kong", "HK", "+852"),
            new("Hungary", "HU", "+36"),
            new("Iceland", "IS", "+354"),
            new("India", "IN", "+91"),
            new("Indonesia", "ID", "+62"),
            new("Iran", "IR", "+98"),
            new("Iraq", "IQ", "+964"),
            new("Ireland", "IE", "+353"),
            new("Isle of Man", "IM", "+44"),
            new("Israel", "IL", "+972"),
            new("Italy", "IT", "+39"),
            new("Jamaica", "JM", "+1"),
            new("Japan", "JP", "+81"),
            new("Jersey", "JE", "+44"),
            new("Jordan", "JO", "+962"),
            new("Kazakhstan", "KZ", "+7"),
            new("Kenya", "KE", "+254"),
            new("Kiribati", "KI", "+686"),
            new("Kosovo", "XK", "+383"),
            new("Kuwait", "KW", "+965"),
            new("Kyrgyzstan", "KG", "+996"),
            new("Laos", "LA", "+856"),
            new("Latvia", "LV", "+371"),
            new("Lebanon", "LB", "+961"),
            new("Lesotho", "LS", "+266"),
            new("Liberia", "LR", "+231"),
            new("Libya", "LY", "+218"),
            new("Liechtenstein", "LI", "+423"),
            new("Lithuania", "LT", "+370"),
            new("Luxembourg", "LU", "+352"),
            new("Macao", "MO", "+853"),
            new("Madagascar", "MG", "+261"),
            new("Malawi", "MW", "+265"),
            new("Malaysia", "MY", "+60"),
            new("Maldives", "MV", "+960"),
            new("Mali", "ML", "+223"),
            new("Malta", "MT", "+356"),
            new("Marshall Islands", "MH", "+692"),
            new("Martinique", "MQ", "+596"),
            new("Mauritania", "MR", "+222"),
            new("Mauritius", "MU", "+230"),
            new("Mayotte", "YT", "+262"),
            new("Mexico", "MX", "+52"),
            new("Micronesia", "FM", "+691"),
            new("Moldova", "MD", "+373"),
            new("Monaco", "MC", "+377"),
            new("Mongolia", "MN", "+976"),
            new("Montenegro", "ME", "+382"),
            new("Montserrat", "MS", "+1"),
            new("Morocco", "MA", "+212"),
            new("Mozambique", "MZ", "+258"),
            new("Myanmar", "MM", "+95"),
            new("Namibia", "NA", "+264"),
            new("Nauru", "NR", "+674"),
            new("Nepal", "NP", "+977"),
            new("Netherlands", "NL", "+31"),
            new("New Caledonia", "NC", "+687"),
            new("New Zealand", "NZ", "+64"),
            new("Nicaragua", "NI", "+505"),
            new("Niger", "NE", "+227"),
            new("Nigeria", "NG", "+234"),
            new("Niue", "NU", "+683"),
            new("Norfolk Island", "NF", "+672"),
            new("North Korea", "KP", "+850"),
            new("North Macedonia", "MK", "+389"),
            new("Northern Mariana Islands", "MP", "+1"),
            new("Norway", "NO", "+47"),
            new("Oman", "OM", "+968"),
            new("Pakistan", "PK", "+92"),
            new("Palau", "PW", "+680"),
            new("Palestine", "PS", "+970"),
            new("Panama", "PA", "+507"),
            new("Papua New Guinea", "PG", "+675"),
            new("Paraguay", "PY", "+595"),
            new("Peru", "PE", "+51"),
            new("Philippines", "PH", "+63"),
            new("Pitcairn", "PN", "+64"),
            new("Poland", "PL", "+48"),
            new("Portugal", "PT", "+351"),
            new("Puerto Rico", "PR", "+1"),
            new("Qatar", "QA", "+974"),
            new("Reunion", "RE", "+262"),
            new("Romania", "RO", "+40"),
            new("Russia", "RU", "+7"),
            new("Rwanda", "RW", "+250"),
            new("Saint Barthelemy", "BL", "+590"),
            new("Saint Helena, Ascension and Tristan da Cunha", "SH", "+290"),
            new("Saint Kitts and Nevis", "KN", "+1"),
            new("Saint Lucia", "LC", "+1"),
            new("Saint Martin (French)", "MF", "+590"),
            new("Saint Pierre and Miquelon", "PM", "+508"),
            new("Saint Vincent and the Grenadines", "VC", "+1"),
            new("Samoa", "WS", "+685"),
            new("San Marino", "SM", "+378"),
            new("Sao Tome and Principe", "ST", "+239"),
            new("Saudi Arabia", "SA", "+966"),
            new("Senegal", "SN", "+221"),
            new("Serbia", "RS", "+381"),
            new("Seychelles", "SC", "+248"),
            new("Sierra Leone", "SL", "+232"),
            new("Singapore", "SG", "+65"),
            new("Sint Maarten (Dutch)", "SX", "+1"),
            new("Slovakia", "SK", "+421"),
            new("Slovenia", "SI", "+386"),
            new("Solomon Islands", "SB", "+677"),
            new("Somalia", "SO", "+252"),
            new("South Africa", "ZA", "+27"),
            new("South Georgia and the South Sandwich Islands", "GS", "+500"),
            new("South Korea", "KR", "+82"),
            new("South Sudan", "SS", "+211"),
            new("Spain", "ES", "+34"),
            new("Sri Lanka", "LK", "+94"),
            new("Sudan", "SD", "+249"),
            new("Suriname", "SR", "+597"),
            new("Svalbard and Jan Mayen", "SJ", "+47"),
            new("Sweden", "SE", "+46"),
            new("Switzerland", "CH", "+41"),
            new("Syria", "SY", "+963"),
            new("Taiwan", "TW", "+886"),
            new("Tajikistan", "TJ", "+992"),
            new("Tanzania", "TZ", "+255"),
            new("Thailand", "TH", "+66"),
            new("Timor-Leste", "TL", "+670"),
            new("Togo", "TG", "+228"),
            new("Tokelau", "TK", "+690"),
            new("Tonga", "TO", "+676"),
            new("Trinidad and Tobago", "TT", "+1"),
            new("Tunisia", "TN", "+216"),
            new("Turkey", "TR", "+90"),
            new("Turkmenistan", "TM", "+993"),
            new("Turks and Caicos Islands", "TC", "+1"),
            new("Tuvalu", "TV", "+688"),
            new("Uganda", "UG", "+256"),
            new("Ukraine", "UA", "+380"),
            new("United Arab Emirates", "AE", "+971"),
            new("United Kingdom", "GB", "+44"),
            new("United States", "US", "+1"),
            new("United States Minor Outlying Islands", "UM", "+1"),
            new("Uruguay", "UY", "+598"),
            new("Uzbekistan", "UZ", "+998"),
            new("Vanuatu", "VU", "+678"),
            new("Vatican City", "VA", "+379"),
            new("Venezuela", "VE", "+58"),
            new("Vietnam", "VN", "+84"),
            new("Virgin Islands (British)", "VG", "+1"),
            new("Virgin Islands (U.S.)", "VI", "+1"),
            new("Wallis and Futuna", "WF", "+681"),
            new("Western Sahara", "EH", "+212"),
            new("Yemen", "YE", "+967"),
            new("Zambia", "ZM", "+260"),
            new("Zimbabwe", "ZW", "+263"),
            new("Aland Islands", "AX", "+358"),
        };

        public static bool IsValidDialCode(string dialCode)
        {
            if (string.IsNullOrWhiteSpace(dialCode))
            {
                return false;
            }

            var normalized = dialCode.Trim();
            return Countries.Any(country => string.Equals(country.DialCode, normalized, StringComparison.Ordinal));
        }
    }
}